spring.application.name=pricing-service

spring.cloud.config.enabled=false

server.port=8082
# add Eureka Client service URL:
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true